--1
CREATE DATABASE IF NOT EXISTS `LEARINING` DEFAULT CHARACTER SET UTF8MB4;
--2
CREATE TABLE `tblLanguages`(
    `id` SMALLINT UNSINGED PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(20) UNIQUE,
)CHARACTER SET LATIN1 ;
--3
CREATE TABLE `tblCourseDefinitions`(
    `id`  MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
    `LanguageId` SMALLINT UNSINGED ,
    `NAME` VARCHAR(100) not null ,
    `REPLICATIONKEY` CHAR(36) CHARACTER SET latin1 UNIQUE not null,
    FOREIGN KEY (`NAME`)
    REFERENCES `tblCourseDefinitions`(`Name`) 
);