CREATE DATABASE IF NOT EXISTS `AP`;
CREATE TABLE `AP`.`AFDELING`
(
	`AFDNR` char(5) PRIMARY KEY,
    `BUDGET` DECIMAL(8,2) NOT NULL,
    `LOCATIE` VARCHAR(30),
    `ISACTIEF` TINYINT UNSIGNED DEFAULT FALSE,
    `GEMPUNTEN` DECIMAL(4,2)
); 
INSERT INTO `AFDELING` VALUES(12345,2000.25,'Campus Ellermanstraat', FALSE ,12.43);

SELECT * FROM `AFDELING`

