--1
SELECT
    SPELERSNR,
    TEAMNR,
    CASE 
        WHEN GEWONNEN > VERLOREN THEN 'GEWONNEN'
        ELSE 'VERLOREN'
    END AS RTESULAAT
FROM 
    WEDSTRIJD;

--2
SELECT 
    SPELERSNR,
    JAARTOE,
    CASE
        WHEN JAARTOE < 1980 THEN 'OUDEREN'
        WHEN JAARTOE >= 1980 AND JAARTOE < 1983 THEN 'JONGEREN'
        ELSE 'KINDEREN'
    END AS GROEP    
FROM
    WEDSTIJDEN

--3
SELECT 
    SPELERSNR,
    JAARTOE,
    CASE
        WHEN JAARTOE < 1980 THEN
        CASE
            WHEN (BONDSNR IS NULL) THEN 'OUDEREN RECREACTIEF'
            ELSE 'OUDEREN WEDSTRIJD'
        END AS

        WHEN JAARTOE >= 1980 AND JAARTOE < 1983 THEN 'JONGEREN'
        ELSE 'KINDEREN'
    END AS GROEP    
FROM
    WEDSTIJDEN