SELECT 
    `NAAM`,
    CONCAT('31(0)',
            RIGHT(`TELEFOON`,
                LENGTH(`TELEFOON`)-1 )) AS INTTELEFOON
FROM
    `SPELERS`;
    
-- 2 

SELECT 
	`SPELERSNR`,
    CASE
		WHEN MONTH(`GEB_DATUM`) = MONTH(CURRENT_DATE) AND DAY(`GEB_DATUM`) = DAY(CURRENT_DATE) THEN 'JARIG'
        ELSE 'NIET JARIG'
    END AS FEEST
FROM
	`SPELERS`