--1
SELECT 
    BETALINGSNR,
    BEDRAG
FROM
    BOETES
WHERE
    BEDRAG IN (50,75,100);
--2
SELECT 
    * 
FROM
    WEDSTRIJDEN;
WHERE
    SPELERSNR NOT IN (8,27,112);
--3
SELECT
    SPELERSNR,
    NAAM,
    STRAAT,
FROM
    SPELERS
WHERE
    LEFT(`NAAM`,1) IN ('e','l','s')

--4
SELECT
    SPELERSNR,
    JAARTOE,
    GEB _DATUM,
    YEAR(CURRENT_DATE) - `JAARTOE` AS AANTAL_JAREN
    CASE
        WHEN YEAR(CURRENT_DATE) - `JAARTOE` >= 45 THEN '45+'
        WHEN YEAR(CURRENT_DATE) - `JAARTOE` >= 40 THEN '40+'
        YEAR(CURRENT_DATE) - `JAARTOE` >= 35 THEN '35+'
        ELSE 
    END AS `DUURTIJD`
FROM
    SPELERS
WHERE
    YEAR(GEB_DATUM) IN (1956,1963,1970)