--1
SELECT
    SPELERSNR,
    NAAM,
    CONCAT('+31(0)',RIGHT(TELEFOONNR,(LENGHT(TELEFOONNR)-1))

    ) AS INTTLEFOON

FROM
    SPELERS

--2 
SELECT
    SPELERSNR,
    CASE
        WHEN (
            MONTH(CURENT_DATE) = MONTH(GEB_DATUM) 
            AND DAY(CURENT_DATE) = DAY(GEB_DATUM) 
        ) THEN 'JARIG' 
        ELSE 'NIET JARIG'
    END AS FEEST
FROM
    SPELERS ;

